### PR TITLE
Draft Issue 20 notifications

### PR DESCRIPTION
**Pull request by rthchldshynee**
This is a draft because right now it just sends emails, but we didn't discuss when they will send and what will trigger them.  Also the db code breaks the server so I had to comment it until it works.  Someone needs to share the working .env file contents and accompanying server code!! don't merge this into main!!

### CODE REVIEW

**Comment by rthchldshynee** [comment]
This PR now contains our postgres db and a basic integration for it.  We're able to connect to it using the values in the .env files, and it's hosted on neon.  It also is integrated into the /users endpoint.

Please leave your thoughts on this here.

**Comment by DmitriiM1** [comment]
I appreciate for your huge work, you did everything perfectly and everything is working great, so I can complete my tasks as soon as possible.

**Comment by rthchldshynee** [comment]
Great to hear Dimitri, I added my search stuff to this, so please check that out as well! and make sure you pull from this branch again if you're going to work from it!

**Comment by rthchldshynee** [comment]
Please note, when you pull the latest now, because I edited the client to hit the server api, you will need two terminals open, one running the server and one running the client.  They must be simultaneously running to get it to work fully now. 

image

**Pull request merged**
